config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#start'
  get "terms" => 'pages#terms'
  get "tasks/:id" => 'pages#show_task'
  
  get 'autocomplete' => 'notes#autocomplete'
  
  resources :notes do  
    resources :attachments
  end
  
  resources :tasks do
    member do
      put 'update_status'
    end
  end
  
 
  

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates  :title, presence: true, length: { maximum: 100 }
  
  
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :attachments, dependent: :destroy
  
  # Vor dem Speichern wird der Inhalt bereinigt um die HTML-Tags 
  # in content_pur gespeichert
  before_save :strip_html_tags
  
  # Nach dem erfolgreichen Speichern werden aus dem Text 
  # die Tags (#...) extrahiert und
  # als solche gespeichert
  after_save  :gen_tags
  
  # Hier können wir für eine Notiz die verwandten Notizen speichern
  attr_reader :related_notes
  attr_writer :related_notes
  
  protected
    def strip_html_tags
      self.content_pur = ActionView::Base.full_sanitizer.sanitize(self.content)
    end
    
    # Generierung der Tags aus dem Inhalt bzw. dem Titel
    def gen_tags
      note_tags = []
      # Tags aus dem Text extrahieren und als Tags speichern
      # und der Notiz zuordnen
      tags = get_tags_from_text(self.content) + get_tags_from_text(self.title)
    
      tags.each do |tag|
        new_tag = find_or_create(self.user_id, tag[0])
        
        note_tags << new_tag
      end
      self.tags = note_tags.uniq
    end
    
    # Vorhandenes Tag verwenden oder neu anlegen
    # Die ActiveRecord-Methode "find_and_create" kann hier nicht verwendet werden,
    # weil wir nicht nach einem Namen sondern nach upper(name) suchen
    # TODO: Prüfen, ob die Methode nicht doch verwendet werden kann.
    def find_or_create(user_id, name)
      new_tag = Tag.new()
      begin
        # Bang-Version, damit "RecordNotFound"-Exception geworfen wird
        new_tag = Tag.where("user_id = ? and upper(name) = upper(?)", user_id, name).take!
      rescue ActiveRecord::RecordNotFound
        new_tag = Tag.create(:user_id => user_id, :name => name)
      end
    end
    
    def get_tags_from_text(text)
      tags = []
      v_text = ""
      # Inhalte innerhalb der <pre>-Tags werden ignoriert,
      # auch über Zeilenumbrüche hinweg (/.../m)
      # durch das ? wird aus ".*" eine non-greedy quantifier
      v_text = text.gsub(/<pre>.*?<\/pre>/m, "")
      # non-word-boundary#word-boundary*word-boundary
      tags = v_text.scan(/\B#(\b\w+\b)/) 
    end
    
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  LIMITER = " & "
  WILDCARD = ":*" 
  
  # Index bzw. Suchmaske
  def index
    
    # alle tags, die mindestens einer Notiz zugeordnet sind
    # TODO: Sortierung nach "lower(name)"
    @tag_cloud = TagCloud.new(current_user.id)
    
    if params[:s].present?  # Suche nach Schlagworten
      @keywords = params[:s]
            
      # Leerzeichen werden durch "&" ersetzt und an jeden Suchbegriff wird ":*" gehängt.
      search = add_wildcard(@keywords)
        
      # Volltextsuche
      where_clause = ["index_col_title_content @@ to_tsquery(?)", search]
      
      # wir suchen nur in den Notizen des aktuell angemeldeten Users
      @notes = current_user.notes.where(where_clause).order(updated_at: :desc)
      
    elsif params[:t].present? # Suche über einen konkreten Tag
      @selected_tag = params[:t]
      
      # Alle Notizen zu einem konkreten Tag
      @notes = current_user.notes.joins(:tags).where("tags.id = ?", @selected_tag).order(updated_at: :desc)
      
    else # kein Suchbegriff, es werden die ersten 10 Notizen gezeigt.
      @notes = current_user.notes.order(updated_at: :desc).limit(10)
    end
    
    
  end
  
  # Detailanzeige
  def show
    @note = find_note(params[:id])
    if @note then
      #format_text(@note.title)
      @tags = @note.tags
      #format_text(@note.content, @tags)
      
      @note.related_notes = current_user.notes.joins(:tags).where('note_id <> ? and tag_id in (select tag_id from notes_tags where note_id = ?)', @note.id, @note.id).order(id: :desc)
    end
  end
  
  # Notiz bearbeiten
  def edit
    #byebug
    @note = find_note(params[:id])
  end
  
  # Update durchführen
  def update
    @note = find_note(params[:id])
    
    if @note.update(note_params)
      flash[:notice] = "'#{@note.title}' #{t :updated}"
      redirect_to @note
    end 
  end
  
  # Neue Notiz anlegen
  def new
    @note = Note.new
    @note.user_id = current_user.id
  end
  
  # Insert durchführen
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if @note.save(note_params)
      flash[:notice] = "'#{@note.title}' #{t :created}"
      redirect_to @note
    end 
  end
  
  def destroy
      @note = find_note(params[:id])
      title = @note.title
      
      @note.destroy
      
      flash[:notice] = "'#{title}' #{t :deleted}"
      redirect_to notes_path
  end
  
  def autocomplete
    @note_titles = []
    if params[:term].present?  # Suche nach Schlagworten
      @keywords = params[:term]
            
      # Leerzeichen werden durch "&" ersetzt und an jeden Suchbegriff wird ":*" gehängt.
      search = add_wildcard(@keywords)
        
      # Volltextsuche
      where_clause = ["index_col_title_content @@ to_tsquery(?)", search]
      
      # wir suchen nur in den Notizen des aktuell angemeldeten Users
      @notes = current_user.notes.select("id, title, content").where(where_clause).order(updated_at: :desc).limit(20)
    
      render :plain => @notes.to_json, :status => 200
    end 
  end
  
  # Private Methoden
  private
  def find_note(id)
    # Auch wenn wir eine konkrete Notiz anzeigen, müssen wir prüfen, ob diese
    # dem angemeldeten User gehört.
    Note.where("id = ? and user_id = ?", id, current_user.id).take
  end
  
  def note_params
    params.require(:note).permit(:title, :content)
  end
  
  # Formatiert den Text (wird nicht mehr verwendet)
  def format_text(text, tags=[])
    if text then
      # " @some text@ " wird zu " <code>some text</code> " inkl. der Blanks
      text.gsub!(/\B@(.*?)@\B/) { |r| "<code>#{$1}</code>"}
    
      # alle tags werden ersetzt durch "<mark>text</mark>"
      tags.each do |tag|
        text.gsub!(/(##{tag.name})/) { |r| "<mark tag_name=#{$1}>#{$1}</mark>"}
      end
      #logger.debug("2. text: #{text}")
    end 
  end
  
  def add_wildcard(keywords)
    keywords_plus = ""
    if keywords.include?(" ") then
      keywords.split(" ").each do |k|
        keywords_plus = keywords_plus + k + WILDCARD + LIMITER
      end
      keywords_plus.chomp(LIMITER)
    else
      keywords + WILDCARD
    end
  end
  
end

app/views/notes/_tags_and_date.haml
%small
  -if updated_at
    %i(class="fa fa-calendar")
    = l updated_at 
    &nbsp;
    
  - if tags.present? then
    %i(class="fa fa-tag")
    - tags.each do |tag|
      = link_to "##{tag.name}", notes_path(t:tag.id)

app/views/notes/_tool_palette.haml
- new_icon ||= false

.tool-palette
  %small
    - if new_icon then
      = link_to(new_note_path, title: t(:create_note)) do
        %i(class="fa fa-plus-square-o")
      
    = link_to(edit_note_path(id), title: t(:edit_note)) do
      %i(class="fa fa-edit")
    = link_to(note_path(id), title: t(:delete_note), method: :delete, data: { confirm: t(:confirm_delete_note)}) do
      %i(class="fa fa-trash-o")
    = link_to("#", title: t(:export_to_pdf_note)) do
      %i(class="fa fa-file-pdf-o")
    = link_to("#", title: t(:mail_note)) do
      %i(class="fa fa-envelope-o")

app/views/notes/edit.haml
%h4

%section
  = form_for(:note, url: note_path, html: { method: :put }) do |f|
    .form-group
      = f.label :title, t(:title)
      = f.text_field :title, autocomplete: "off", placeholder: t(:title), class: "form-control  text-bold-large", size:80
     

    .form-group
      = f.label :content, t(:content)
      = hidden_field_tag "note[content]", "#{find_and_preserve(@note.content)}", id:"note_content"
      %trix-editor{:input=>"note_content", autofocus: true, :placeholder=>t(:content), :class => "trix-content"}
    
      %div      
        %button{:id => "update", :type => "submit", :class=>"btn btn-primary"}
          %i{:class=>"fa fa-file-text"}
          = t(:save)
            
            
%script
  = "attach_document('#{form_authenticity_token}');"
  
  

app/views/notes/index.haml
#tag-cloud
  - @tag_cloud.html.each do |tag|
    = raw tag

#new-note
  = link_to(new_note_path, title: t(:create_note), class: "btn") do
    %i(class="fa fa-plus")
    =t(:create_note)
        

#search-results
  %ul(class = "list-group")
    - @notes.each do |note|
      %li(class = "list-group-item")
        %h4
          = link_to raw(extract_result(note.title, @keywords)), note_path(note.id)
          = render :partial => "tool_palette", :locals => {:id => note.id}
          .subheading
            = render :partial => "tags_and_date", :locals => {:tags => note.tags, :updated_at => note.updated_at} 
            
            
        .list-item-content  
          =  raw extract_result(note.content_pur, @keywords, " ... ")
          

app/views/notes/new.haml
%h4
 
%section
  = form_for(:note, url: notes_path, html: { method: :post }) do |f|
  
    .form-group
      = f.label :title, t(:title)
      = f.text_field :title, autocomplete: "off", autofocus: true, placeholder: t(:title), class: "form-control text-bold-large", size:80
      
    .form-group
      = f.label :content, t(:content)
      = f.hidden_field :content
      %trix-editor{:input=>"note_content", :placeholder=>t(:content), :class => "trix-content"}
      
    %button{:id => "update", :type => "submit", :class=>"btn"}
      %i{:class=>"fa fa-file-text"}
      = t(:create)

%script
  = "attach_document('#{form_authenticity_token}', '#{t(:no_attachment)}');"
  

app/views/notes/show.haml
- if @note then
  .content
    %h3
      = @note.title if @note
      .subheading
        = render :partial => "tags_and_date", :locals => {:tags => @note.tags, :updated_at => @note.updated_at} 
        = render :partial => "tool_palette", :locals => {:id => @note.id, :new_icon => true}
      
    %section
      .trix-content(class="trix-show")
        = find_and_preserve @note.content.html_safe

  .sidebar(id="related-notes")
    %h4
      %i(class="fa fa-tags")
      = t :related_notes

    %ul(class="list-group")
      - @note.related_notes.each do |note|
        %li(class="list-group-item")
          %h5
            = link_to note.title, note_path(note.id)
            %br
            = render :partial => "tags_and_date", :locals => {:tags => note.tags, :updated_at => note.updated_at}
    
- else
  .page-header
    %h3
      = t :note_not_found