config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#start'
  get "terms" => 'pages#terms'
  get "tasks/:id" => 'pages#show_task'
  
  get 'autocomplete' => 'notes#autocomplete'
  
  resources :notes do  
    resources :attachments
  end
  
  resources :tasks do
    member do
      put 'update_status'
    end
  end
  
 
  

end

app/views/layouts/_breadcrumb.haml
%ol{:class=>"breadcrumb"}
  %li
    %a{:href=>"/"}
      = t :home
  %li
    %a{:href=>"#"}
      = t :sign_up
  

app/views/layouts/_footer.haml
#footer
  .container
    .content-50-left
      %div{:class=>"text-left"}
        %span
          %a{:href=>"#", 'data-toggle'=>"modal", 'data-target'=>"#AboutUs"}
            %i{:class=>"fa fa-info-circle"}
            = t :about_us
        %span
          %a{ :href=>terms_path}
            %i{:class=>"fa fa-legal"}
            = t :terms
        %span
          %a{ :href=>"#", 'data-toggle'=>"modal", 'data-target'=>"#help", 'rel'=>"nofollow"}
            %i{:class=>"fa fa-question-circle"}
            = t :help
            
    .content-50-right
      %div{:class=>"text-right"}
        %i{:class=>"fa fa-copyright"}
        2016 - Bernd C. Toepfer

app/views/layouts/_header.haml
%header(class = "site-header")
  .wrap
    .container         
      #logo
        .logo
          %a{class: "logo", href: root_path}
            =image_tag("GmTD50.svg", title: "Back to Start", alt: "Start", :height=>"50px")
     
      #search-form
        = form_for(:note, url: notes_path, :html => {:class=>"form-inline", :role => "search", :method => :get}) do |f|
          .form-group
            = f.text_field :keywords,  autofocus: true, placeholder: t(:search_for), class: "form-control",  type: "search", size:80, name:"s", value: @keywords
      #nav
        %nav(class="nav")
          = render 'layouts/navigation'

app/views/layouts/_help.haml
%div{:class=>"modal fade", :id=>"help", 'tabindex'=>"-1", :role=>"dialog", 'aria-labelledby'=>"Hilfe", 'aria-hidden'=>"true"}
  .modal-dialog
    .modal-content    
      .modal-header
        %button{:type=>"button", :class=>"close", 'data-dismiss'=>"modal", 'aria-label'=>"Close"}
          %span{'aria-hidden'=>"true"}
            &times;
        %h1{:class=>"modal-title"}
          =t :help
      
      .modal-body
        = render 'devise/shared/links_complete'
        
        
      .modal-footer
        %div{:class=>"col-xs-12 padded"}
          %button{:type=>"button", :class=>"btn btn-primary", 'data-dismiss'=>"modal", 'aria-label'=>"Close"}
            %span{'aria-hidden'=>"true"}
            %i{:class=>"fa fa-close"}
            = t :close
            

app/views/layouts/_impressum.haml
%div{:class=>"modal fade", :id=>"Impressum", 'tabindex'=>"-1", :role=>"dialog", 'aria-labelledby'=>"Impressum", 'aria-hidden'=>"true"}
  .modal-dialog
    .modal-content    
      .modal-header
        %button{:type=>"button", :class=>"close", 'data-dismiss'=>"modal", 'aria-label'=>"Close"}
          %span{'aria-hidden'=>"true"}
            &times;
        %h1{:class=>"modal-title"}
          =t :terms
      
      .modal-body
        %h4
          BC. Toepfer - Software Engineering
        %p
          Bernd C. Toepfer
          %br
          Diestelstraße 18c
          %br
          D-22397 Hamburg
        %p
          Telefon: 040/60 68 59 56
          %br
          Telefax: 040/60 68 59 57
          %br
          E-Mail: 
          %a{ :href=>"mailto:bernd@bctoepfer.de"}
            bernd@bctoepfer.de
          %br
        %h4
          Inhaltlich verantwortlich
        %p
          Inhaltlich Verantwortlicher gemäß § 55 Abs. 2 RStV: 
          %strong
            Bernd Toepfer
          
        %h4
          Haftungsausschluss
        %p
        Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.
        
        
      .modal-footer
        %div{:class=>"col-xs-12 padded"}
          %button{:type=>"button", :class=>"btn btn-primary", 'data-dismiss'=>"modal", 'aria-label'=>"Close"}
            %span{'aria-hidden'=>"true"}
            %i{:class=>"fa fa-close"}
            = t :close
            

app/views/layouts/_messages.haml
-unless flash.empty?
  #message(class="text-center")
    -flash.each do |name, msg| 
      -if msg.is_a?(String)
        %div{:class=>"alert alert-#{name == "notice" ? "success" : "danger"}"}
          %div{id:"flash_#{name}"}
            %i{:class=>"fa #{name == "notice" ? "fa-check" : "fa-times"}"}
            = msg

app/views/layouts/_navigation.haml
%ul{:class=>"nav"}
  %li
    %a(class="toggle-nav fa fa-bars" href="#")

.nav-mobile
  %ul{:class=>"nav"}
    %li
      %a{:href=>"#"}
        %i{:class=>"fa fa-book"}
        = t :projects
    %li
      %a{:href=>tasks_path}
        %i{:class=>"fa fa-check"}
        = t :tasks
    %li
      %a{:href=>notes_path}
        %i{:class=>"fa fa-file-text"}
        = t :notes
    %li
      &nbsp;&nbsp;
        
    - if  user_signed_in?
      %li
        %a{:href=>edit_user_registration_path}
          %i{:class=>"fa fa-user"}
          = t :account
      %li
        = link_to t(:log_out), destroy_user_session_path, method: :delete

app/views/layouts/_searching.haml
#searching
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, s

app/views/layouts/application.haml
/ <!DOCTYPE html>
!!! 5
%html
  %head
    %meta{ 'name' => "viewport", 'content' => "width=device-width, initial-scale=1.0, maximum-scale=2.0"}
    %title
      = "GmTD V5.0"
      
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    
  %body{:id => "GmTD5"}
    = render 'layouts/header'
    
    .wrap
      .container   
        = yield
        
      
      //Am Ende, damit diese Box den Inhalt ueberlagert.
      = render 'layouts/messages'
            
    = render 'layouts/footer'

    
    
    
  %script
    $("#message").delay(3000).addClass("in").fadeOut(1000);
    toggle_menu();
    add_autocomplete("#{autocomplete_path}", "#{notes_path}/");


  